"""add feedback table

Revision ID: 0cf0de538e6a
Revises: 8a76e40d3b3b
Create Date: 2026-06-07 10:12:40.592765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf0de538e6a'
down_revision: Union[str, Sequence[str], None] = '8a76e40d3b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('feedback_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', name='feedbacktype'), nullable=False),
    sa.Column('chunk_ids', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_document_id'), 'feedback', ['document_id'], unique=False)
    op.create_index(op.f('ix_feedback_workspace_id'), 'feedback', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_workspace_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_document_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
